#!/bin/bash
## A cmake configuration call for a FailBochs pruning
EXP=$1
FAILPATH=$(dirname $0)/..
if [ -z $1 ]; then
    echo "Experiment not set. Usage: $0 <experiment name>"
    echo "Existing experiments:"
    find ${FAILPATH}/src/experiments -maxdepth 1 -mindepth 1 -type d -printf \-\>\ %P\\n | sort
else

    CONFIG='-DBUILD_BOCHS:BOOL=ON -DBUILD_X86:BOOL=ON -DBUILD_GEM5:BOOL=OFF -DBUILD_ARM:BOOL=OFF -DBUILD_SIMULAVR:BOOL=OFF -DBUILD_AVR:BOOL=OFF -DCONFIG_BOCHS_NO_ABORT:BOOL=ON -DCONFIG_EVENT_BREAKPOINTS:BOOL=ON -DCONFIG_EVENT_BREAKPOINTS_RANGE:BOOL=ON -DCONFIG_EVENT_INTERRUPT:BOOL=ON -DCONFIG_EVENT_IOPORT:BOOL=ON -DCONFIG_EVENT_MEMREAD:BOOL=ON -DCONFIG_EVENT_MEMWRITE:BOOL=ON -DCONFIG_EVENT_TRAP:BOOL=ON -DCONFIG_SR_RESTORE:BOOL=ON -DCONFIG_SR_SAVE:BOOL=ON -DEXPERIMENTS_ACTIVATED:STRING='${EXP}' -DBUILD_IMPORT_TRACE:BOOL=ON -DBUILD_PRUNE_TRACE:BOOL=ON -DBUILD_LLVM_DISASSEMBLER=OFF -DBUILD_CAPSTONE_DISASSEMBLER=ON -DBUILD_AVR=OFF -DBUILD_SIMULAVR=OFF -DPLUGINS_ACTIVATED=tracing;serialoutput'

#    if [ -e "${FAILPATH}/src/experiments/${EXP}/config.cmake" ]; then
#        CONFIG="-C ${FAILPATH}/src/experiments/${EXP}/config.cmake -DEXPERIMENTS_ACTIVATED:STRING=${EXP}"
#    fi

    cmake ${CONFIG} ${FAILPATH}
fi
