// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InjectionPointStepsMessage.proto

#ifndef PROTOBUF_INCLUDED_InjectionPointStepsMessage_2eproto
#define PROTOBUF_INCLUDED_InjectionPointStepsMessage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_InjectionPointStepsMessage_2eproto 

namespace protobuf_InjectionPointStepsMessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_InjectionPointStepsMessage_2eproto
class InjectionPointMessage;
class InjectionPointMessageDefaultTypeInternal;
extern InjectionPointMessageDefaultTypeInternal _InjectionPointMessage_default_instance_;
namespace google {
namespace protobuf {
template<> ::InjectionPointMessage* Arena::CreateMaybeMessage<::InjectionPointMessage>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class InjectionPointMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:InjectionPointMessage) */ {
 public:
  InjectionPointMessage();
  virtual ~InjectionPointMessage();

  InjectionPointMessage(const InjectionPointMessage& from);

  inline InjectionPointMessage& operator=(const InjectionPointMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InjectionPointMessage(InjectionPointMessage&& from) noexcept
    : InjectionPointMessage() {
    *this = ::std::move(from);
  }

  inline InjectionPointMessage& operator=(InjectionPointMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InjectionPointMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InjectionPointMessage* internal_default_instance() {
    return reinterpret_cast<const InjectionPointMessage*>(
               &_InjectionPointMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InjectionPointMessage* other);
  friend void swap(InjectionPointMessage& a, InjectionPointMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InjectionPointMessage* New() const final {
    return CreateMaybeMessage<InjectionPointMessage>(NULL);
  }

  InjectionPointMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InjectionPointMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InjectionPointMessage& from);
  void MergeFrom(const InjectionPointMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InjectionPointMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 injection_instr = 1;
  bool has_injection_instr() const;
  void clear_injection_instr();
  static const int kInjectionInstrFieldNumber = 1;
  ::google::protobuf::uint32 injection_instr() const;
  void set_injection_instr(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:InjectionPointMessage)
 private:
  void set_has_injection_instr();
  void clear_has_injection_instr();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 injection_instr_;
  friend struct ::protobuf_InjectionPointStepsMessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InjectionPointMessage

// required uint32 injection_instr = 1;
inline bool InjectionPointMessage::has_injection_instr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InjectionPointMessage::set_has_injection_instr() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InjectionPointMessage::clear_has_injection_instr() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InjectionPointMessage::clear_injection_instr() {
  injection_instr_ = 0u;
  clear_has_injection_instr();
}
inline ::google::protobuf::uint32 InjectionPointMessage::injection_instr() const {
  // @@protoc_insertion_point(field_get:InjectionPointMessage.injection_instr)
  return injection_instr_;
}
inline void InjectionPointMessage::set_injection_instr(::google::protobuf::uint32 value) {
  set_has_injection_instr();
  injection_instr_ = value;
  // @@protoc_insertion_point(field_set:InjectionPointMessage.injection_instr)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_InjectionPointStepsMessage_2eproto
