// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InjectionPointStepsMessage.proto

#include "InjectionPointStepsMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class InjectionPointMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InjectionPointMessage>
      _instance;
} _InjectionPointMessage_default_instance_;
namespace protobuf_InjectionPointStepsMessage_2eproto {
static void InitDefaultsInjectionPointMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_InjectionPointMessage_default_instance_;
    new (ptr) ::InjectionPointMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::InjectionPointMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_InjectionPointMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInjectionPointMessage}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_InjectionPointMessage.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::InjectionPointMessage, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::InjectionPointMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::InjectionPointMessage, injection_instr_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::InjectionPointMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_InjectionPointMessage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "InjectionPointStepsMessage.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n InjectionPointStepsMessage.proto\"0\n\025In"
      "jectionPointMessage\022\027\n\017injection_instr\030\001"
      " \002(\r"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 84);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "InjectionPointStepsMessage.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_InjectionPointStepsMessage_2eproto

// ===================================================================

void InjectionPointMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InjectionPointMessage::kInjectionInstrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InjectionPointMessage::InjectionPointMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_InjectionPointStepsMessage_2eproto::scc_info_InjectionPointMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:InjectionPointMessage)
}
InjectionPointMessage::InjectionPointMessage(const InjectionPointMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  injection_instr_ = from.injection_instr_;
  // @@protoc_insertion_point(copy_constructor:InjectionPointMessage)
}

void InjectionPointMessage::SharedCtor() {
  injection_instr_ = 0u;
}

InjectionPointMessage::~InjectionPointMessage() {
  // @@protoc_insertion_point(destructor:InjectionPointMessage)
  SharedDtor();
}

void InjectionPointMessage::SharedDtor() {
}

void InjectionPointMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InjectionPointMessage::descriptor() {
  ::protobuf_InjectionPointStepsMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_InjectionPointStepsMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InjectionPointMessage& InjectionPointMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_InjectionPointStepsMessage_2eproto::scc_info_InjectionPointMessage.base);
  return *internal_default_instance();
}


void InjectionPointMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:InjectionPointMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  injection_instr_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool InjectionPointMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:InjectionPointMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 injection_instr = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_injection_instr();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &injection_instr_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:InjectionPointMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:InjectionPointMessage)
  return false;
#undef DO_
}

void InjectionPointMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:InjectionPointMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 injection_instr = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->injection_instr(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:InjectionPointMessage)
}

::google::protobuf::uint8* InjectionPointMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:InjectionPointMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 injection_instr = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->injection_instr(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:InjectionPointMessage)
  return target;
}

size_t InjectionPointMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:InjectionPointMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required uint32 injection_instr = 1;
  if (has_injection_instr()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->injection_instr());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InjectionPointMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:InjectionPointMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const InjectionPointMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InjectionPointMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:InjectionPointMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:InjectionPointMessage)
    MergeFrom(*source);
  }
}

void InjectionPointMessage::MergeFrom(const InjectionPointMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:InjectionPointMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_injection_instr()) {
    set_injection_instr(from.injection_instr());
  }
}

void InjectionPointMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:InjectionPointMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InjectionPointMessage::CopyFrom(const InjectionPointMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:InjectionPointMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InjectionPointMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void InjectionPointMessage::Swap(InjectionPointMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InjectionPointMessage::InternalSwap(InjectionPointMessage* other) {
  using std::swap;
  swap(injection_instr_, other->injection_instr_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InjectionPointMessage::GetMetadata() const {
  protobuf_InjectionPointStepsMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_InjectionPointStepsMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::InjectionPointMessage* Arena::CreateMaybeMessage< ::InjectionPointMessage >(Arena* arena) {
  return Arena::CreateInternal< ::InjectionPointMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
